### ISSUE TITLE
Jython not detected

### ISSUE THREAD

**Issue by cyberdelia** [kennethreitz-archive/its.py#4]
In latest Jython release 2.7.0a1, version string doesn't contain `"jython"`.
Here is what `sys.version.lower()` returns :

```
2.7a1 (default:4f5e3c12edc0, may 16 2012, 13:40:33) \n[java hotspot(tm) 64-bit server vm (apple inc.)]
```

**Comment by kennethreitz** [comment]
Hmm, i there something else we can use to detect that?

Perhaps just `java` in that string.

**Comment by cyberdelia** [comment]
I've checked with previous jython version `2.5.2`, here is what `sys.version.lower()` returns :

```
2.5.2 (release_2_5_2:7206, mar 2 2011, 23:12:06) \n[java hotspot(tm) 64-bit server vm (apple inc.)]
```

I think we can safely check `java` rather than `jython`.
