### ISSUE TITLE
If you ever feel like adding support for IBM S390 on Linux ...

### ISSUE THREAD

**Issue by pombredanne** [kennethreitz-archive/its.py#7]
I once played last year on such as beast ... and I had kept these details:
# Z/os returns: sys.platform = linux2 and os.uname=('Linux', 'l003064', '2.6.9-42.EL', '#1 SMP Wed Jul 12 23:21:43 EDT 2006', 's390x') on 64bits
# and sys.platform = linux2 and os.uname=('Linux', 'l003064', '2.6.9-42.EL', '#1 SMP Wed Jul 12 23:21:43 EDT 2006', 's390') on 32bits

**Comment by medecau** [comment]
It's been over a year without replies or PRs.

Close?
